apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordle-duel-service-redis-data-longhorn
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
