apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordle-duel-service-redis-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
