apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: lab-home
  namespace: flux-system
spec:
  image: dariomr8/lab-home
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: lab-home
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
  imageRepositoryRef:
    name: lab-home
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: wordle-duel
  namespace: flux-system
spec:
  image: dariomr8/wordle-duel
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: wordle-duel
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
  imageRepositoryRef:
    name: wordle-duel
  policy:
    semver:
      range: ">=0.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: wordle-duel-service
  namespace: flux-system
spec:
  image: dariomr8/wordle-duel-service
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: wordle-duel-service
  namespace: flux-system
spec:
  filterTags:
    extract: ""
    pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
  imageRepositoryRef:
    name: wordle-duel-service
  policy:
    semver:
      range: ">=0.0.0"
