apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "72.*"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        retention: 30d
        scrapeInterval: 30s
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        additionalScrapeConfigs:
          - job_name: spring-boot
            metrics_path: /actuator/prometheus
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names: [apps]
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: "true"
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                target_label: __address__
              - source_labels: [__meta_kubernetes_pod_label_app]
                action: replace
                target_label: app
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
    grafana:
      admin:
        existingSecret: grafana-admin-secret
        userKey: admin-user
        passwordKey: admin-password
      "grafana.ini":
        server:
          root_url: "https://dariolab.com/grafana/"
          serve_from_sub_path: true
      persistence:
        enabled: true
        size: 2Gi
        storageClassName: local-path
      initChownData:
        enabled: false
      securityContext:
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      ingress:
        enabled: false
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          folderAnnotation: grafana_folder
          provider:
            foldersFromFilesStructure: false
        datasources:
          enabled: true
          uid: prometheus
      additionalDataSources:
        - name: Loki
          type: loki
          uid: loki
          url: http://loki.observability.svc.cluster.local:3100
          access: proxy
          isDefault: true
    prometheus-node-exporter:
      enabled: true
    kube-state-metrics:
      enabled: true
