apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- apps.yaml
- cert-manager-resources.yaml
- infrastructure.yaml
- observability.yaml
patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |
      - op: add
        path: /spec/postBuild
        value:
          substitute:
            DOMAIN: dariolab.com
