apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: "0.*"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    alloy:
      configMap:
        create: false
        name: alloy-config
        key: config.alloy
    controller:
      type: daemonset
    extraVolumes:
      - name: traefik-logs
        hostPath:
          path: /var/log/traefik
          type: DirectoryOrCreate
    extraVolumeMounts:
      - name: traefik-logs
        mountPath: /var/log/traefik
        readOnly: true
