apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=dario.mauri9@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.bouncer.version=v1.4.1"
    persistence:
      enabled: true
    volumes:
      - name: access-logs
        mountPath: /var/log/traefik
        type: hostPath
        path: /var/log/traefik
        hostPathType: DirectoryOrCreate
      - name: crowdsec-bouncer-key
        mountPath: /etc/traefik/crowdsec
        type: secret
    ingressRoute:
      dashboard:
        enabled: false
