apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=dario.mauri9@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      - "--experimental.plugins.bouncer.version=v1.4.1"
      - "--providers.kubernetescrd.allowCrossNamespace=true"
    deployment:
      kind: Deployment
      replicas: 1
      strategy:
        type: Recreate
      additionalVolumes:
        - name: plugins-storage
          emptyDir: {}
        - name: access-logs
          hostPath:
            path: /var/log/traefik
            type: DirectoryOrCreate
        - name: crowdsec-bouncer-key
          secret:
            secretName: crowdsec-bouncer-key
    additionalVolumeMounts:
      - name: plugins-storage
        mountPath: /plugins-storage
      - name: access-logs
        mountPath: /var/log/traefik
      - name: crowdsec-bouncer-key
        mountPath: /etc/traefik/crowdsec
        readOnly: true
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
    service:
      type: ClusterIP
    persistence:
      enabled: true
    ingressRoute:
      dashboard:
        enabled: false
