apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/apps.yaml
  - storageclasses/local-path.yaml
  - storageclasses/longhorn.yaml
  - cert-manager/namespace.yaml
  - cert-manager/helmrepository.yaml
  - cert-manager/helmrelease.yaml
  - longhorn/namespace.yaml
  - longhorn/helmrepository.yaml
  - longhorn/helmrelease.yaml
  - traefik/helmchartconfig.yaml
  - traefik/default-headers.yaml
  - traefik/rate-limit.yaml
  - traefik/log-truncate-cronjob.yaml
  - crowdsec/namespace.yaml
  - crowdsec/helmrepository.yaml
  - crowdsec/helmrelease.yaml
  - crowdsec/pvc-config-longhorn.yaml
  - crowdsec/pvc-data-longhorn.yaml
  - crowdsec/acquis.yaml
  - crowdsec/whitelist.yaml
  - crowdsec/bouncer-middleware.yaml
  - kubernetes-dashboard/namespace.yaml
  - kubernetes-dashboard/helmrepository.yaml
  - kubernetes-dashboard/helmrelease.yaml
  - kubernetes-dashboard/admin-user.yaml
  - kubernetes-dashboard/ingressroute.yaml
  - geoipupdate/cronjob.yaml
