apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces/apps.yaml
  - traefik/helmchartconfig.yaml
  - traefik/default-headers.yaml
  - traefik/rate-limit.yaml
  - crowdsec/namespace.yaml
  - crowdsec/helmrepository.yaml
  - crowdsec/helmrelease.yaml
  - crowdsec/acquis.yaml
  - crowdsec/bouncer-middleware.yaml
  - kubernetes-dashboard/namespace.yaml
  - kubernetes-dashboard/helmrepository.yaml
  - kubernetes-dashboard/helmrelease.yaml
  - kubernetes-dashboard/admin-user.yaml
  - kubernetes-dashboard/ingressroute.yaml
