apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crowdsec-db-pvc-longhorn
  namespace: crowdsec
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
