apiVersion: v1
kind: ConfigMap
metadata:
  name: wordle-duel-service-config
  namespace: apps
data:
  TZ: "Europe/Prague"
  SPRING_DATA_REDIS_HOST: "wordle-duel-service-redis"
  SPRING_DATA_REDIS_PORT: "6379"
