apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: wordle-duel-cors
  namespace: apps
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
    accessControlAllowOriginList:
      - https://dariolab.com
    addVaryHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wordle-duel
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`${WORDLE_DUEL_DOMAIN}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: wordle-duel
          port: 80
      middlewares:
        - name: crowdsec-bouncer
        - name: wordle-duel-cors
        - name: default-headers
        - name: rate-limit-app
  tls:
    store:
      name: default
      namespace: kube-system
