apiVersion: batch/v1
kind: CronJob
metadata:
  name: geoipupdate
  namespace: kube-system
spec:
  schedule: "0 */3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: geoipupdate
              image: ghcr.io/maxmind/geoipupdate:v7.1.1
              env:
                - name: GEOIPUPDATE_ACCOUNT_ID
                  valueFrom:
                    secretKeyRef:
                      name: geoipupdate-secret
                      key: account-id
                - name: GEOIPUPDATE_LICENSE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: geoipupdate-secret
                      key: license-key
                - name: GEOIPUPDATE_EDITION_IDS
                  value: GeoLite2-City
              volumeMounts:
                - name: geoip-data
                  mountPath: /usr/share/GeoIP
          restartPolicy: OnFailure
          volumes:
            - name: geoip-data
              hostPath:
                path: /var/lib/geoipupdate
                type: DirectoryOrCreate
