apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-secrets
  namespace: crowdsec
type: Opaque
stringData:
  bouncer-key: "CHANGE_ME"    # openssl rand -hex 32
  enroll-key: "CHANGE_ME"     # from https://app.crowdsec.net (optional)
---
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-bouncer-key
  namespace: kube-system
type: Opaque
stringData:
  bouncer-key: "CHANGE_ME"    # MUST match bouncer-key above
