apiVersion: v1
kind: Secret
metadata:
  name: wordle-duel-service-secrets
  namespace: apps
type: Opaque
stringData:
  DB_USER: "CHANGE_ME"
  DB_PORT: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  WORDLE_GOOGLE_CLIENT_ID: "CHANGE_ME"
  WORDLE_GOOGLE_CLIENT_SECRET: "CHANGE_ME"
  WORDLE_JWT_PRIVATE_KEY_PEM: |
    -----BEGIN PRIVATE KEY-----
    CHANGE_ME
    -----END PRIVATE KEY-----
  WORDLE_JWT_PUBLIC_KEY_PEM: |
    -----BEGIN PUBLIC KEY-----
    CHANGE_ME
    -----END PUBLIC KEY-----
